/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package taboadataddeoprenotazionegita;

/**
 *
 * @author taboada.taddeo
 */
public class AggiuntaStudente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiuntaStudente.class.getName());
    private String nome, cognome;
    private int id, idGita;

    /**
     * Creates new form AggiuntaStudente
     */
    public AggiuntaStudente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCognome = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();
        lblIdGita = new javax.swing.JLabel();
        txtIdGita = new javax.swing.JTextField();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiungi uno Studente");
        setMinimumSize(new java.awt.Dimension(500, 350));

        pnlTitolo.setBackground(new java.awt.Color(153, 255, 255));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Aggiungi uno Studente!");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBackground(new java.awt.Color(153, 255, 255));
        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentro.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setText("ID:");
        pnlCentro.add(lblId);

        txtId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtId);

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setText("Nome:");
        pnlCentro.add(lblNome);

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtNome);

        lblCognome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCognome.setText("Cognome:");
        pnlCentro.add(lblCognome);

        txtCognome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtCognome);

        lblIdGita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIdGita.setText("ID Gita:");
        pnlCentro.add(lblIdGita);

        txtIdGita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlCentro.add(txtIdGita);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlConferma.setBackground(new java.awt.Color(153, 255, 255));
        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setBackground(new java.awt.Color(102, 255, 102));
        btnConferma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        id = Integer.parseInt(txtId.getText());
        nome = txtNome.getText();
        cognome = txtCognome.getText();
        idGita = Integer.parseInt(txtIdGita.getText());
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    public String getNome() {
        return nome;
    }

    public String getCognome() {
        return cognome;
    }

    public int getId() {
        return id;
    }

    public int getIdGita() {
        return idGita;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdGita;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdGita;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
