/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taboadataddeoprenotazionegita;

import javax.swing.table.*;

/**
 *
 * @author taboada.taddeo
 */
public class FrameGita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameGita.class.getName());
    private Gita g;
    private GestioneFile gF;
    private DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Luogo"}, 10);
    

    /**
     * Creates new form FrameGita
     */
    public FrameGita() {
        initComponents();
        g = new Gita();
        gF = new GestioneFile();
        impostaTabella();
    }
    
    private void impostaTabella() {
        tblVisualizza.setSize(pnlSinistra.getWidth(), pnlSinistra.getHeight());
        tblVisualizza.setModel(model);
        tblVisualizza.setRowHeight(pnlSinistra.getHeight() / tblVisualizza.getRowCount());
    }
    
    public void aggiornaGite() { 
        model.setRowCount(0);
        /*
        for (Studente s : a.getListaStudenti()) {
            model.addRow(new Object[]{s.getMatricola(), s.getNome(), s.getCognome()});
        }
        */
        cmbGite.addItem("gita");
    }
    
    public void rimuoviStudente() {
        int rS = tblVisualizza.getSelectedRow();
        /*
        if (rS != -1) {
            String matricola = (String) model.getValueAt(rS, 0);
            a.eliminaStudente(matricola);
            model.removeRow(rS);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlSinistra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizza = new javax.swing.JTable();
        pnlCentro = new javax.swing.JPanel();
        cmbGite = new javax.swing.JComboBox<>();
        pnlDestra = new javax.swing.JPanel();
        btnRimuoviStudente = new javax.swing.JButton();
        btnAggiungiGita = new javax.swing.JButton();
        btnRimuoviGita = new javax.swing.JButton();
        btnAggiungiStudente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prenotazione Gita");

        pnlTitolo.setBackground(new java.awt.Color(153, 255, 255));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Prenotazione Gita");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlMain.setBackground(new java.awt.Color(153, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlSinistra.setBackground(new java.awt.Color(153, 255, 255));
        pnlSinistra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gite", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(153, 0, 0))); // NOI18N
        pnlSinistra.setPreferredSize(new java.awt.Dimension(400, 500));
        pnlSinistra.setLayout(new java.awt.BorderLayout());

        tblVisualizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizza);

        pnlSinistra.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlMain.add(pnlSinistra, java.awt.BorderLayout.WEST);

        pnlCentro.setBackground(new java.awt.Color(153, 255, 255));
        pnlCentro.setPreferredSize(new java.awt.Dimension(300, 532));
        pnlCentro.setLayout(null);

        cmbGite.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        pnlCentro.add(cmbGite);
        cmbGite.setBounds(40, 30, 240, 70);
        cmbGite.getAccessibleContext().setAccessibleDescription("");

        pnlMain.add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlDestra.setBackground(new java.awt.Color(153, 255, 255));
        pnlDestra.setPreferredSize(new java.awt.Dimension(300, 100));
        pnlDestra.setLayout(null);

        btnRimuoviStudente.setBackground(new java.awt.Color(255, 102, 102));
        btnRimuoviStudente.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRimuoviStudente.setText("Rimuovi Studente");
        btnRimuoviStudente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRimuoviStudenteActionPerformed(evt);
            }
        });
        pnlDestra.add(btnRimuoviStudente);
        btnRimuoviStudente.setBounds(40, 430, 230, 70);

        btnAggiungiGita.setBackground(new java.awt.Color(102, 255, 102));
        btnAggiungiGita.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAggiungiGita.setText("Aggiungi Gita");
        btnAggiungiGita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiGitaActionPerformed(evt);
            }
        });
        pnlDestra.add(btnAggiungiGita);
        btnAggiungiGita.setBounds(40, 30, 230, 70);

        btnRimuoviGita.setBackground(new java.awt.Color(255, 102, 102));
        btnRimuoviGita.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRimuoviGita.setText("Rimuovi Gita");
        btnRimuoviGita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRimuoviGitaActionPerformed(evt);
            }
        });
        pnlDestra.add(btnRimuoviGita);
        btnRimuoviGita.setBounds(40, 130, 230, 70);

        btnAggiungiStudente.setBackground(new java.awt.Color(102, 255, 102));
        btnAggiungiStudente.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAggiungiStudente.setText("Aggiungi Studente");
        btnAggiungiStudente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiStudenteActionPerformed(evt);
            }
        });
        pnlDestra.add(btnAggiungiStudente);
        btnAggiungiStudente.setBounds(40, 330, 230, 70);

        pnlMain.add(pnlDestra, java.awt.BorderLayout.EAST);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiungiGitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiGitaActionPerformed
        AggiuntaGita aG = new AggiuntaGita(this, true);
        aG.setLocationRelativeTo(null);
        aG.setVisible(true);
        
        int id = aG.getId();
        String luogo = aG.getLuogo();
        
        //a.aggiungiStudente(new Studente(matricola, nome, cognome));
        aggiornaGite();
    }//GEN-LAST:event_btnAggiungiGitaActionPerformed

    private void btnRimuoviGitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRimuoviGitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRimuoviGitaActionPerformed

    private void btnAggiungiStudenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiStudenteActionPerformed
        AggiuntaStudente aS = new AggiuntaStudente(this, true);
        aS.setLocationRelativeTo(null);
        aS.setVisible(true);
        
        int id = aS.getId();
        String nome = aS.getNome();
        String cognome = aS.getCognome();
        
        //a.aggiungiStudente(new Studente(matricola, nome, cognome));
    }//GEN-LAST:event_btnAggiungiStudenteActionPerformed

    private void btnRimuoviStudenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRimuoviStudenteActionPerformed
        rimuoviStudente();
    }//GEN-LAST:event_btnRimuoviStudenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungiGita;
    private javax.swing.JButton btnAggiungiStudente;
    private javax.swing.JButton btnRimuoviGita;
    private javax.swing.JButton btnRimuoviStudente;
    private javax.swing.JComboBox<String> cmbGite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlDestra;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSinistra;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTable tblVisualizza;
    // End of variables declaration//GEN-END:variables
}
