/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package taboadataddeoprenotazionegita;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author tadde
 */
public class SceltaFile extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SceltaFile.class.getName());
    private String file;

    /**
     * Creates new form SceltaFile
     */
    public SceltaFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.file = null;
        fileScelto();
    }

    public void fileScelto() {
        jfcSceltaTesto.addActionListener(e -> {
            if (JFileChooser.APPROVE_SELECTION.equals(e.getActionCommand())) {
                File fileScelto = jfcSceltaTesto.getSelectedFile();

                    if (fileScelto.getName().endsWith(".dat")) {
                        file = fileScelto.getAbsolutePath();
                        dispose();
                    } else {
                        lblErrore.setText("Errore: il file selezionato non è un file di testo (.dat)");
                    }
            }
        });
    }
    public void cambiaTesto(){
        if(lblTitolo.getText().equals("Scegli il File delle Gite da aprire:")){
            lblTitolo.setText("Scegli il File degli Studenti da aprire:");
        }
        else{
            lblTitolo.setText("Scegli il File delle Gite da aprire:");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        lblAttenzione = new javax.swing.JLabel();
        pnlScelta = new javax.swing.JPanel();
        jfcSceltaTesto = new javax.swing.JFileChooser();
        pnlErrore = new javax.swing.JPanel();
        lblErrore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scegli File");

        pnlTitolo.setBackground(new java.awt.Color(153, 255, 255));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Scegli il File delle Gite da aprire:");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        lblAttenzione.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAttenzione.setForeground(new java.awt.Color(204, 0, 0));
        lblAttenzione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttenzione.setText("Attenzione! Questa scelta cambierà i dati attualmente impostati");
        pnlTitolo.add(lblAttenzione, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlScelta.setBackground(new java.awt.Color(153, 255, 255));
        pnlScelta.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlScelta.setMinimumSize(new java.awt.Dimension(500, 500));
        pnlScelta.setLayout(new java.awt.BorderLayout());

        jfcSceltaTesto.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlScelta.add(jfcSceltaTesto, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlScelta, java.awt.BorderLayout.CENTER);

        pnlErrore.setBackground(new java.awt.Color(153, 255, 255));
        pnlErrore.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlErrore.setPreferredSize(new java.awt.Dimension(610, 50));
        pnlErrore.setLayout(new java.awt.BorderLayout());

        lblErrore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblErrore.setForeground(new java.awt.Color(204, 0, 0));
        lblErrore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlErrore.add(lblErrore, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnlErrore, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getFile() {
        return file;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jfcSceltaTesto;
    private javax.swing.JLabel lblAttenzione;
    private javax.swing.JLabel lblErrore;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlErrore;
    private javax.swing.JPanel pnlScelta;
    private javax.swing.JPanel pnlTitolo;
    // End of variables declaration//GEN-END:variables
}
